name: 'File Copy'
description: 'Pretends to copy some files and return the number of files copied'
inputs:
  tenantId:  # path
    description: 'The environment to deploy to'
    required: true
outputs:
  copied-files: 
    description: "Number of files copied"
    value: ${{ steps.random-number-generator.outputs.filesNo }}
runs:
  using: "composite"
  steps: 
    - id: random-number-generator
      run: echo "::set-output name=filesNo::$(echo $RANDOM)"
      shell: bash
    # - name: 'Terraform: Setup Authentication'
    #   run: |
    #     echo "ARM_CLIENT_ID=${{ steps.azureKeyVault.outputs.automationClientId }}" >> $GITHUB_ENV
    #     echo "ARM_CLIENT_SECRET=${{ steps.azureKeyVault.outputs.automationClientSecret }}" >> $GITHUB_ENV
    #     echo "ARM_SUBSCRIPTION_ID=${{ steps.azureKeyVault.outputs.subscriptionId }}" >> $GITHUB_ENV
    #     echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
      # shell: bash
    - uses: hashicorp/setup-terraform@v1
      name: 'Terraform: Version Pin'
      with:
        terraform_version: ${{ env.tf_version }}
    - run: env | sort
      name: 'Environment: Sort'
      shell: bash
    - run: | 
        echo ${{ inputs.tenantId }}
        terraform --version
      name: 'Environment: Sort'
      shell: bash
  