name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  - tf_version: '1.0.6'
jobs:
  plan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test, prod]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      name: 'Code: Checkout'
    - uses: hashicorp/setup-terraform@v1
      name: 'Terraform: Download'
      with:
        terraform_version: ${{ env.tf_version }}
    - name: 'Terraform: Plan ${{ matrix.environment }}'
      run: terraform --version
