name: Terraform IaC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  prod_env: [dev, test, prod]
  runner: 'ubuntu-latest'
  tf_version: '1.0.6'
  tf_working_dir: 'infra'


jobs:
  Plan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: ${{ env.prod_env }}
    # env:
    #   TF_VARS_environment:  ${{ matrix.env }}
    steps:
    - uses: actions/checkout@v2
      name: 'Code: Checkout'
    - uses: azure/login@v1
      name: 'Azure: Login'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Azure: Get Secrets'
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: 'kv-dev-mgrlabstf'
        secrets: 'automationClientSecret, automationClientId, subscriptionId'
      id: azureKeyVault
    - name: 'Azure: Logout'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear

    - uses: hashicorp/setup-terraform@v1
      name: 'Terraform: Download v${{ env.tf_version }}'
      with:
        terraform_version: ${{ env.tf_version }}
    - name: 'Terraform: Setup Authentication'
      run: |
        echo "ARM_CLIENT_ID=${{ steps.azureKeyVault.outputs.automationClientId }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ steps.azureKeyVault.outputs.automationClientSecret }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ steps.azureKeyVault.outputs.subscriptionId }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

    - name: 'Terraform: Init'
      run: terraform -chdir=${{ env.tf_working_dir }} init

    - name: 'Terraform: Plan'
      run: terraform -chdir=${{ env.tf_working_dir }} plan -var-file=env/${{ matrix.env }}.tfvars -out=tf${{ matrix.env }}.plan

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.env }}_plan
        path: ${{ env.tf_working_dir }}/tf${{ matrix.env }}.plan