
name: Terraform - Composite

on: [workflow_dispatch]

env:
  runner: 'ubuntu-latest'
  tf_version: '1.0.6'
  tf_working_dir: 'infra'

jobs:
  planDev:
    runs-on: ubuntu-latest
    env:
      environment: 'dev'
    name: Terraform Plan - Dev
    steps:
    - uses: actions/checkout@v2
    - id: terraformPlan
      name: 'Terraform Workflow'
      uses: ./.github/templates/terraform
      with:
        azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
        tenantId: ${{ secrets.AZURE_TENANT_ID }}
