name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  plan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test, prod]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5
    - name: Plan ${{ matrix.environment }}
      run: terraform --version
