name: Terraform IaC

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ["dev", "test", "prod"]

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      name: 'Terraform: Pin Version'
      with:
        terraform_version: 1.0.5
    - run: |
        echo ${{ matrix.environment }}
        terraform --version
      name: Terraform: Plan ${{ matrix.environment }}
