name: Terraform IaC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  runner: 'ubuntu-latest'
  tf_version: '1.0.6'
  tf_working_dir: 'infra'


jobs:
  Plan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test, prod]

    steps:
    - uses: actions/checkout@v2
      name: 'Code: Checkout'
    - uses: hashicorp/setup-terraform@v1
      name: 'Terraform: Download v${{ env.tf_version }}'
      with:
        terraform_version: ${{ env.tf_version }}
    - name: 'Terraform: Plan ${{ matrix.env }}'
      run: |
        terraform --version
