name: Terraform IaC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  runner: 'ubuntu-latest'
  tf_version: '1.0.6'
  tf_working_dir: 'infra'


jobs:
  Plan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, test, prod]

    steps:
    - uses: actions/checkout@v2
      name: 'Code: Checkout'
    - uses: azure/login@v1
      name: 'Azure: Login "${{ matrix.env }}" Environment'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: hashicorp/setup-terraform@v1
      name: 'Terraform: Download v${{ env.tf_version }}'
      with:
        terraform_version: ${{ env.tf_version }}

    - name: 'Terraform: Init'
      run: terraform -chdir=${{ env.tf_working_dir }} init

    - name: 'Terraform: Plan'
      run: terraform -chdir=${{ env.tf_working_dir }} plan -var-file=env/${{ matrix.env }}.tfvars
