
name: Composite Example

on: [workflow_dispatch]

env:
  runner: 'ubuntu-latest'
  tf_version: '1.0.6'
  tf_working_dir: 'infra'

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: 'Azure: Login'
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Download the required secrets
    - name: 'Azure: Get Secrets'
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: 'kv-dev-mgrlabstf'
        secrets: 'automationClientSecret, automationClientId, subscriptionId'
      id: azureKeyVault
    - id: terraformPlan
      name: 'Terraform Workflow'
      uses: ./.github/templates/terraform
      with:
        tenantId: ${{ secrets.AZURE_TENANT_ID }}
        environment: 'dev'
    - run: echo Files copied ${{ steps.myCompositeAction.outputs.copied-files }} 
      shell: bash
